### ISSUE TITLE
Missing file ?

### ISSUE THREAD

**Issue by pclucas14** [Mattdl/ContinualPrototypeEvolution#1]
Hi, 

I'm trying to include your method as a baseline for a research project. I tried running the code following the `.sh` file, and I'm getting the following error 

```
lpagec@dp-gpu2[ContinualPrototypeEvolution](main)$python main.py --tasks_to_preserve 5 --save_path results/cifar10/ --data_path ./data --log_every 100 --samples_per_task 10000 --data_file cifar10.pt --cuda yes --model prototypical.CoPE --batch_size 10 --lr 0.005 --loss_T 0.1 --p_momentum 0.99 --n_memories 100 --n_outputs 256 --n_iter 1 --n_seeds 5 demo_CIFAR10
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import metrics.plot as plot
  File "/home/ml/users/lpagec/pytorch/ContinualPrototypeEvolution/metrics/plot.py", line 4, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'
```

Is this a file you created ? Or is there a package called utils that you are using ?

Thanks, 
Lucas

**Comment by pclucas14** [comment]
@Mattdl tagging you in case your notifications are off :)

**Comment by YoungBigBird1985** [comment]
I get the same issue when running the command...Please help address this..

**Comment by Mattdl** [comment]
Hi @pclucas14 @YoungBigBird1985 , thanks for reporting the issue, and sorry for the late reply, I was just on holidays. 
It was a refactoring issue,  but the issue should be fixed now.
Let me know if you encounter any other problems!
